name: Grabb_And_Merge

on:
  schedule:
    - cron: '0 */3 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
env:
  GH_USERNAME: ${{ github.actor }}
  CHANNEL_NAME: 'euronews'
  CHANNEL_LIST: 'iptv_liste'
  
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Grab euronews
        run: |
          git config --global user.name "${GH_USERNAME}"
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config user.email 
          git config user.name
          git rm ${CHANNEL_NAME}.m3u
          git commit -am "${CHANNEL_NAME}.m3u deleted"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -f ${CHANNEL_NAME}.m3u
          git status
          git commit -m "${CHANNEL_NAME}.m3u playlist updated."
          git push

      - name: Grab DW
        run: |
          gh workflow run Grabb_DW
          
      - name: Merge Files
        run: |
          git rm ${CHANNEL_LIST}.m3u
          git commit -am "${CHANNEL_LIST}.m3u deleted"
          chmod +x exec_mergeFiles.sh && ./exec_mergeFiles.sh
          git add -f ${CHANNEL_LIST}.m3u
          git status
          git commit -m "${CHANNEL_LIST}.m3u playlist updated."
          git push
